all:
  vars:
    ansible_user: noiro
  children:
    deployment:
      hosts:
        kkolla01:
          ansible_host: 192.168.1.200
          kolla_primary_interface_address: 192.168.1.200/24
    controller:
      hosts:
        kkolla01:
    compute_nodes:
      hosts:
        kkolla02:
          ansible_host: 192.168.1.201
          kolla_primary_interface_address: 192.168.1.201/24
        kkolla03:
          ansible_host: 192.168.1.202
          kolla_primary_interface_address: 192.168.1.202/24
    control:
      children:
        controller: {}
    network:
      children:
        controller: {}
    loadbalancer:
      children:
        controller: {}
    mariadb:
      children:
        controller: {}
    rabbitmq:
      children:
        controller: {}
    compute:
      children:
        compute_nodes: {}
    monitoring:
      children:
        controller: {}
    glance-api:
      children:
        controller: {}
    heat-api:
      children:
        controller: {}
    heat-api-cfn:
      children:
        controller: {}
    heat-engine:
      children:
        controller: {}
    horizon:
      children:
        controller: {}
    keystone:
      children:
        controller: {}
    fluentd:
      children:
        controller: {}
    placement-api:
      children:
        controller: {}
    kolla-toolbox:
      children:
        controller: {}
        compute_nodes: {}
    kolla-logs:
      children:
        controller: {}
        compute_nodes: {}
    memcached:
      children:
        controller: {}
    cron:
      children:
        controller: {}
    haproxy:
      children:
        controller: {}
    ovn-nb-db:
      children:
        controller: {}
    ovn-sb-db:
      children:
        controller: {}
    ovn-northd:
      children:
        controller: {}
    ovn-sb-db-relay:
      children:
        controller: {}
    ovn-controller:
      children:
        compute_nodes: {}
    ovn-controller-network:
      hosts: {}
    ovn-controller-compute:
      hosts: {}
    openvswitch:
      children:
        compute_nodes: {}
    neutron-server:
      children:
        controller: {}
    neutron-ovn-agent:
      children:
        compute_nodes: {}
    neutron-ovn-metadata-agent:
      children:
        compute_nodes: {}
    neutron-cisco-topology-agent:
      children:
        compute_nodes: {}
    ironic-api:
      children:
        controller: {}
    ironic-conductor:
      children:
        controller: {}
