all:
  vars:
    ansible_user: noiro
  children:
    deployment:
      hosts:
        kkolla01:
          ansible_host: 172.25.235.200
          kolla_primary_interface_address: 172.25.235.200/24
    control:
      hosts:
        kkolla01:
    network:
      hosts:
        kkolla01:
    loadbalancer:
      hosts:
        kkolla01:
    mariadb:
      hosts:
        kkolla01:
    rabbitmq:
      hosts:
        kkolla01:
    compute:
      hosts:
        kkolla02:
          ansible_host: 172.25.235.201
          kolla_primary_interface_address: 172.25.235.201/24
        kkolla03:
          ansible_host: 172.25.235.202
          kolla_primary_interface_address: 172.25.235.202/24
    monitoring:
      hosts:
        kkolla01:
    glance-api:
      hosts:
        kkolla01:
    heat-api:
      hosts:
        kkolla01:
    heat-api-cfn:
      hosts:
        kkolla01:
    heat-engine:
      hosts:
        kkolla01:
    horizon:
      hosts:
        kkolla01:
    keystone:
      hosts:
        kkolla01:
    fluentd:
      hosts:
        kkolla01:
    placement-api:
      hosts:
        kkolla01:
    kolla-toolbox:
      hosts:
        kkolla01:
        kkolla02:
        kkolla03:
    kolla-logs:
      hosts:
        kkolla01:
        kkolla02:
        kkolla03:
    memcached:
      hosts:
        kkolla01:
    cron:
      hosts:
        kkolla01:
    haproxy:
      hosts:
        kkolla01:
    ovn-nb-db:
      hosts:
        kkolla01:
    ovn-sb-db:
      hosts:
        kkolla01:
    ovn-northd:
      hosts:
        kkolla01:
    ovn-sb-db-relay:
      hosts:
        kkolla01:
    ovn-controller:
      hosts:
        kkolla02:
        kkolla03:
    ovn-controller-network:
      hosts: {}
    ovn-controller-compute:
      hosts: {}
    openvswitch:
      hosts:
        kkolla02:
        kkolla03:
    neutron-server:
      hosts:
        kkolla01:
    neutron-ovn-agent:
      hosts:
        kkolla02:
        kkolla03:
    neutron-ovn-metadata-agent:
      hosts:
        kkolla02:
        kkolla03:
    neutron-cisco-topology-agent:
      hosts:
        kkolla02:
        kkolla03:
    ironic-api:
      hosts:
        kkolla01:
    ironic-conductor:
      hosts:
        kkolla01:
